"""Report generation per recommendations/report-output-model.md.

One findings store, two audiences, zero mixing: the executive summary contains
no sys_ids; the technical report contains full evidence and scoring traces.
Reports are pure functions of the ScanResult.
"""
from __future__ import annotations

from collections import defaultdict

from .engine import ScanResult

P1_CAP = 10
_SEV_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Informational": 4}
_PRI_ORDER = {"P1": 0, "P2": 1, "P3": 2, "P4": 3}


def _accepted_section(result: ScanResult) -> str:
    accepted = [f for f in result.findings if f.accepted]
    if not accepted:
        return "No accepted risks are registered for this instance."
    lines = [f"{len(accepted)} finding(s) carry a formally accepted risk (reported, not hidden; acceptance expires and forces re-decision):", ""]
    for f in accepted:
        lines.append(f"- {f.title}: {f.accepted_reason}")
    lines.append("")
    return "\n".join(lines)


def backlog_csv(result: ScanResult) -> str:
    """Backlog export per report-output-model.md: one row per finding."""
    import csv
    import io

    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["ID", "Title", "Theme", "Severity", "Priority", "Remediability", "FixPackRef", "Effort", "EffortAssumptions", "SuggestedOwner", "RemediationSummary", "Dependencies", "EvidenceCount", "Accepted"])
    for f in _sorted_findings(result):
        w.writerow([
            f.fingerprint,
            f.title,
            f.category,
            f.score.final_severity,
            f.score.final_priority,
            f.tier,
            f.fixpack_ref or "",
            f.score.effort,
            f.score.effort_assumptions,
            f.owner,
            f.remediation.split(". ")[0],
            "; ".join(f.dependencies),
            f.evidence_total,
            "yes" if f.accepted else "",
        ])
    return buf.getvalue()


def _metric(result: ScanResult, rule_id: str) -> str:
    """One executive-safe number sourced from a rule's finding (no sys_ids)."""
    for f in result.findings:
        if f.rule_id == rule_id and f.evidence:
            return f.evidence[0].summary
    return "no finding raised"


def _sorted_findings(result: ScanResult):
    return sorted(
        result.findings,
        key=lambda f: (_PRI_ORDER[f.score.final_priority], _SEV_ORDER[f.score.final_severity], f.rule_id),
    )


def _themes(result: ScanResult) -> dict[str, list]:
    themes: dict[str, list] = defaultdict(list)
    for f in result.findings:
        themes[f.category].append(f)
    return dict(sorted(themes.items()))


def executive_summary(result: ScanResult) -> str:
    findings = _sorted_findings(result)
    sev = result.by_severity
    pri = result.by_priority
    solvable = [f for f in result.findings if not f.tier.startswith("T3")]
    with_pack = [f for f in result.findings if f.fixpack_ref]
    p1s = [f for f in findings if f.score.final_priority == "P1"]

    upg = [f for f in result.findings if f.category == "Upgrade Readiness"]
    upg_statement = (
        "No upgrade readiness findings were raised in this scan."
        if not upg
        else (
            f"{len(upg)} upgrade readiness findings were raised. The most significant: "
            + "; ".join(f.why_it_matters.split(".")[0].strip() for f in upg[:2])
            + ". Addressing these before the next family release materially reduces upgrade risk and effort."
        )
    )

    lines = [
        "# ROB Executive Summary",
        "",
        f"Instance: {result.snapshot.instance_id} | Snapshot: {result.snapshot.taken_at} | Rule library: {len(result.rule_versions)} rules",
        "",
        "## Instance Health Headline",
        "",
        (
            f"This scan raised {len(result.findings)} findings across technical debt, security, upgrade readiness "
            f"and CMDB/CSDM quality. {pri.get('P1', 0)} require urgent attention (P1). "
            f"{len(with_pack)} findings ship with a ready-to-apply fix generated by ROB; "
            f"{len(solvable)} of {len(result.findings)} are solvable with ROB assistance, the remainder need "
            "design decisions by your teams."
        ),
        "",
        "## Key Numbers",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Findings by severity | " + ", ".join(f"{k}: {sev[k]}" for k in ["Critical", "High", "Medium", "Low", "Informational"] if k in sev) + " |",
        f"| Urgent (P1) findings | {pri.get('P1', 0)} |",
        f"| Solve ratio (fix ready / total) | {len(with_pack)} / {len(result.findings)} |",
        f"| Privileged access exposure | {_metric(result, 'ROB-SEC-001')} |",
        f"| Baseline divergence (worst area) | {_metric(result, 'ROB-UPG-002')} |",
        f"| CMDB trust indicator | {_metric(result, 'ROB-CMDB-001')} |",
        "",
        "## Top Risks",
        "",
    ]
    shown = p1s[:P1_CAP]
    if len(p1s) > P1_CAP:
        lines.append(f"{len(p1s)} P1 findings exist; the top {P1_CAP} are shown, ranked by severity and blast radius.")
        lines.append("")
    for i, f in enumerate(shown, 1):
        fix = "Fix ready to apply." if f.fixpack_ref else ("Requires design work." if f.tier.startswith("T3") else "Assisted fix available on request.")
        lines += [
            f"**{i}. {f.title}** ({f.score.final_severity})  ",
            f"{f.why_it_matters} {fix} Suggested owner: {f.owner}.",
            "",
        ]
    lines += ["## Remediation Themes", ""]
    for theme, fs in _themes(result).items():
        packs = sum(1 for f in fs if f.fixpack_ref)
        efforts = {f.score.effort for f in fs}
        top_pri = min((f.score.final_priority for f in fs), key=lambda p: _PRI_ORDER[p])
        lines.append(
            f"- **{theme}** - {len(fs)} finding(s), priority {top_pri}, "
            f"effort {'/'.join(sorted(efforts))}, {packs} fix(es) ready."
        )
    lines += [
        "",
        "## Upgrade Readiness Statement",
        "",
        upg_statement,
        "",
        "## Accepted Risks and Exclusions",
        "",
        _accepted_section(result),
        "Scan scope: the 4 MVP domains; Workflow/Flow migration analysis, performance and process domains "
        "are out of scan scope this cycle.",
        "",
        "## Recommended Next Cycle",
        "",
        "Apply the ready fix-packs on a sub-production instance, convert P1/P2 findings into backlog items, "
        "and re-scan in 30 days to measure movement.",
        "",
        "---",
        "*Finding references: " + ", ".join(f"[{i+1}] {f.fingerprint}" for i, f in enumerate(shown)) + "*",
    ]
    return "\n".join(lines)


def technical_report(result: ScanResult, knowledge=None) -> str:
    """knowledge: an optional KnowledgeBase. Absent, the report is unchanged;
    present, each finding gains links to the official documentation and to any
    matching best-practice asset."""
    findings = _sorted_findings(result)
    lines = [
        "# ROB Technical Findings Report",
        "",
        "## Scan Manifest",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Instance | {result.snapshot.instance_id} |",
        f"| Snapshot taken | {result.snapshot.taken_at} |",
        f"| Rules executed | {len(result.rule_versions)} ({', '.join(sorted(result.rule_versions))}) |",
        f"| Tables in snapshot | {', '.join(sorted(result.snapshot.tables))} |",
        f"| Findings | {len(result.findings)} |",
        f"| Fix-packs generated | {len(result.fixpacks)} |",
        f"| Rules skipped | {'; '.join(result.skipped_rules) if result.skipped_rules else 'none'} |",
        f"| Extraction gaps | {'; '.join(e.splitlines()[0] for e in result.snapshot.agg('extraction_errors', [])) or 'none'} |",
        "",
        "## Findings",
        "",
    ]
    for f in findings:
        t = f.score
        lines += [
            f"### {f.title}",
            "",
            f"**Rule** {f.rule_id} v{f.rule_version} | **Category** {f.category} | **Severity** {t.final_severity} | "
            f"**Priority** {t.final_priority} | **Remediability** {f.tier} | **Affected area** `{f.affected_area}`",
            "",
            "**Evidence** "
            + (f"(showing {len(f.evidence)} of {f.evidence_total} matches)" if f.evidence_total > len(f.evidence) else f"({f.evidence_total} match(es))"),
            "",
        ]
        for ev in f.evidence:
            ref = f" [`{ev.record_ref}`]" if ev.record_ref else ""
            lines.append(f"- {ev.summary}{ref}")
        refs = knowledge.for_finding(f.to_dict()) if knowledge else []
        if refs:
            lines += ["", "**Further reading**", ""]
            for r in refs:
                label = "official documentation" if r.source == "servicenow-docs" else "best practices library"
                link = f"[{r.title}]({r.url})" if r.url else r.title
                local = f" (local copy: `{r.local_path}`)" if r.local_path else ""
                lines.append(f"- {link} - {label}{local}")
        lines += [
            "",
            f"**Why it matters** {f.why_it_matters}",
            "",
            f"**Recommended remediation** {f.remediation}",
            "",
            f"**Optimisation opportunity** {f.optimisation}",
            "",
            f"**Estimated effort** {t.effort} ({t.effort_assumptions})",
            "",
            f"**Suggested owner** {f.owner}",
            "",
            f"**Fix-pack** {f.fixpack_ref or ('n/a - design work (T3)' if f.tier.startswith('T3') else 'not generated in this run')}",
            "",
            "**Scoring transparency** "
            f"Impact {t.impact} x Likelihood {t.likelihood} -> {t.matrix_severity}"
            + (f"; modifiers: {', '.join(t.modifiers_applied)}" if t.modifiers_applied else "")
            + f" -> {t.final_severity}. Effort {t.effort} -> {t.base_priority}"
            + (f"; adjustments: {', '.join(t.adjustments_applied)}" if t.adjustments_applied else "")
            + f" -> {t.final_priority}.",
            "",
            "---",
            "",
        ]
    lines += ["## Fix-Pack Index", ""]
    if not result.fixpacks:
        lines.append("No fix-packs generated in this run.")
    for p in result.fixpacks:
        lines += [
            f"### {p.name}",
            "",
            f"Finding: `{p.finding_fingerprint}` | Fix artefact: `{p.fix_artefact_filename}` | Backout: `{p.backout_filename}`",
            "",
            f"**Scope** {p.scope_statement}",
            "",
            "**Application instructions**",
            "",
            *(f"{line}" for line in p.instructions.splitlines()),
            "",
        ]
    lines += [
        "## False-Positive Feedback",
        "",
        "Mark any disputed finding with its fingerprint and the reason; disputes feed rule tuning and the "
        "A3 noise measurement.",
    ]
    return "\n".join(lines)
